stream.rules = [
    {   matches = [
            {
                # all keys must match the value. ! negates. ~ starts regex.
                #application.name       = "pw-cat"
                #node.name 		= "~Google Chrome$"
            }
        ]
        actions = {
            update-props = {
                #node.latency = 512/48000
            }
        }
    }
]
