alsa.properties = {
    #alsa.deny = false
    # ALSA params take a single value, an array [] of values
    # or a range { min=.. max=... }
    #alsa.access = [ MMAP_INTERLEAVED MMAP_NONINTERLEAVED RW_INTERLEAVED RW_NONINTERLEAVED ]
    #alsa.format = [ FLOAT S32 S24 S24_3 S16 U8 ]
    #alsa.rate = { min=1 max=384000 }		# or [ 44100 48000 .. ]
    #alsa.channels = { min=1 max=64 }		# or [ 2 4 6 .. ]
    #alsa.period-bytes = { min=128 max=2097152 } # or [ 128 256 1024 .. ]
    #alsa.buffer-bytes = { min=256 max=4194304 } # or [ 256 512 4096 .. ]

    #alsa.volume-method = cubic			# linear, cubic
}
