context.properties = {
    ## Configure properties in the system.
    support.dbus                          = true
    link.max-buffers                       = 16                  # version < 3 clients can't handle more
    mem.warn-mlock                        = false
    mem.allow-mlock                       = true
    mem.mlock-all                         = false
    clock.power-of-two-quantum            = true
    log.level                             = 2
    cpu.zero.denormals                    = true

    #thread.affinity = [ 0 1 ]    # optional array of CPUs
    context.num-data-loops = -1   # -1 = num-cpus, 0 = no data loops

    core.daemon = true              # listening for socket connections
    core.name   = pipewire-0        # core name and socket name

    ## Properties for the DSP configuration.
    default.clock.rate          = 48000
    default.clock.allowed-rates = [ 48000 ]
    default.clock.quantum       = 1024
    default.clock.min-quantum   = 256
    default.clock.max-quantum   = 2048
    default.clock.quantum-limit = 8192
    default.clock.quantum-floor = 128
    default.video.width         = 1920
    default.video.height        = 1080
    default.video.rate.num      = 60
    default.video.rate.denom    = 1

    settings.check-quantum      = true
    settings.check-rate         = true

    # Disable automatic gain control
    api.libcamera.disable = false
    api.v4l2.disable = false
    
    # For ALSA backend
    api.alsa.disable-mmap = false
}
