add_newline = true

[line_break]
disabled = true

[python]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[c]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true
